apiVersion: v1
kind: ReplicationController
metadata:
  name: ntp-server
  labels:
    name: ntp-server
spec: 
  replicas: 1
  selector:
    name: ntp-server
  template:
    metadata:
      labels:
        name: ntp-server
    spec:
      containers: 
      - name: ntp-server
        image: wcen/docker-ntp:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 123
          protocol: UDP
        volumeMounts:
        - mountPath: /etc/chrony
          name: config-volume
        securityContext:
          privileged: true
      volumes:
      - name: config-volume
        configMap:
          name: ntp-config
