apiVersion: v1
kind: Service
metadata:
  name: ntp-server
  labels:
    name: ntp-server
spec:
  type: ClusterIP
  ports:
  - port: 123
    protocol: UDP
    targetPort: 123
  selector:
    name: ntp-server
#  externalIPs:
#    - "192.168.33.26"
